import { Factory } from "./Factory.model";

export class ChillerMaster{
    public id;
    public pageNumber:number;
    public pageSize:number;
    public searchValue:string;
    public entityType:string;
    public chillerId;
    public chillerName:string;
    public fullCapacity;
    public halfCapacity:any;
    public noOfRails;
    public chillerHr;
    public costPerMin;
    public factoryMaster: Factory;
    public chillerDailyLogList: any[] = [];
    public logDate:any;
    public listFor:any;
    public filterDate:any;
    public utilization;
    public factoryId;
    public isDeactivate;
    public loadclosedTime;
    public factoryUserList:any[]=[];
    public factory:any[];
    public remarks;
    public desireTemperature;
    public status;
    public isActualSequence;
    public masterOrder;
    public totalCarcassLoaded;
    public temperature;
    public loadedBy;
    public loadingStartTime;
    public closedBy;
    public loadCloseDateTime;
    public loadClosedTime;
    public unloadclosedTime;
    public isStarted;
    public hotDebone;
    public chillerMaster:any={};
    public date
    public reportFor;
    public rangeDates:Date[];
    public fromDate:any;
    public toDate:any;
    public unLoadRemarks;
    public actualUnloadBy;
    public chiller;
    public underUtilizationRemark;
    public logDates:any;
    public isUtilization;
    public unloadRemarks;
    public unloadDateTime;
    public unloadBy;
    public startDateTime:Date;
    public noOfTrolleys:string;
    public totalCapacityUsed:string;
    public chillerStatusName:string;
}